name: Create release

on:
  push:
    tags:
      - 'v**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    - name: Replace Version in csproj files
      run: |
        $tag = "${{ github.ref }}" -replace '^v', '' # Remove 'v' prefix from the tag
        Get-ChildItem -Path . -Filter *.csproj -Recurse | ForEach-Object {
          $csprojContent = Get-Content $_.FullName -Raw
          $csprojContent -replace "<Version>.*?<\/Version>", "<Version>$tag<\/Version>" | Set-Content $_.FullName
        }
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --configuration Release --no-build
    - name: Pack
      run: dotnet pack PipelineBlocks/PipelineBlocks.csproj --configuration Release --no-build
    - name: Publish
      run: dotnet nuget push **/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGETAPIKEY }}
